sudo: required

services:
  - docker

install:
  - mkdir .ssh && chmod 700 .ssh
  - ssh-keygen -t rsa -N "" -f .ssh/id_rsa
  - cp .ssh/id_rsa id_rsa.priv
  - docker run -d -p 2222:22 -v $(pwd)/.ssh:/root/.ssh/ robertdebock/docker-centos-openssh

script:
  - echo "Runnning tests." ; bats tests/

after_script:
  - docker inspect --format='{{.State.Pid}}' $(docker ps -ql)
  - docker ps | wc -l

notifications:
  email: false
