sudo: required

services:
  - docker

install:
  - mkdir .ssh && chown 700 .ssh
  - ssh-keygen -t rsa -N "" -f $(pwd)/.ssh/id_rsa
  - docker run -p 2222:22 -v $(pwd)/.ssh:/root/.ssh/ robertdebock/docker-centos-openssh 

script:
  - echo "Runnning tests." ; bats tests/

notifications:
  email: false
