sudo: required

services:
  - docker

install:
  - mkdir .ssh && chmod 700 .ssh
  - ssh-keygen -t rsa -N "" -f .ssh/id_rsa
  - docker run -d -p 2222:22 -v $(pwd)/.ssh:/root/.ssh/ robertdebock/docker-centos-openssh
  - sleep 5
  - docker logs $(docker ps -ql)
  - docker run -v $(pwd)/.ssh:/root/.ssh/ robertdebock/docker-centos-openssh /bin/bash -c "ls -l /root/.ssh/ ; chown -R root:root /root/.ssh/ ; ls -l /root/.ssh"
  - ssh -i .ssh/id_rsa -o Port=2222 -o "StrictHostKeyChecking no" root@localhost "id"

script:
  - echo "Runnning tests." ; bats tests/

notifications:
  email: false
