sudo: required

services:
  - docker

install:
  - mkdir .ssh && chmod 700 .ssh
  - ssh-keygen -t rsa -N "" -f .ssh/id_rsa
  - cp .ssh/id_rsa id_rsa.priv
  - docker build -t $TRAVIS_REPO_SLUG:$TRAVIS_BUILD_ID .
  - docker-compose up -d
  - docker run -d -p 2222:22 -v $(pwd)/.ssh:/root/.ssh/ $TRAVIS_REPO_SLUG:$TRAVIS_BUILD_ID

script:
  - echo "Runnning tests." ; bats tests/
  - echo "Running lint." ; docker run -it --rm --privileged -v $(pwd):/root/ projectatomic/dockerfile-lint dockerfile_lint --permissive -f Dockerfile

notifications:
  email: false
