sudo: required

services:
  - docker

install:
  - mkdir .ssh && chmod 700 .ssh
  - ssh-keygen -t rsa -N "" -f .ssh/id_rsa
  - cp .ssh/id_rsa id_rsa.priv
  - docker-compose build
  - docker-compose up -d
  - docker ps

script:
  - echo "Runnning tests." ; bats tests/
  - echo "Running lint." ; docker run -it --rm --privileged -v $(pwd):/root/ projectatomic/dockerfile-lint dockerfile_lint --permissive -f Dockerfile

notifications:
  email: false
