version: '3'
services:
  server:
    image: robertdebock/docker-centos-openssh
    build: .
    volumes:
      - ./.ssh:/root/.ssh/
    ports:
      - "2222:22"
  importkeys:
    image: robertdebock/docker-centos-openssh
    volumes:
      - ./tests/importkeys:/root/.ssh/
    ports:
      - "2223:22"
